version: "3.7"
services:
  well-boot-admin:
    build:
      context: ./
      dockerfile: docker/Dockerfile.boot-admin
    image: 'zxk175/well-boot-admin:${VERSION}'
    container_name: 'well-boot-admin'
    ports:
      - "8010:8010"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

  well-zuul:
    build:
      context: ./
      dockerfile: docker/Dockerfile.zuul
    image: 'zxk175/well-zuul:${VERSION}'
    container_name: 'well-zuul'
    ports:
      - "9000:9000"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

  well-provider-user:
    build:
      context: ./
      dockerfile: docker/Dockerfile.provider-user
    image: 'zxk175/well-provider-user:${VERSION}'
    container_name: 'well-provider-user'
    ports:
      - "9010:9010"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

networks:
  cloud:
    driver: bridge