version: "3.7"
services:
  well-boot-admin:
    build:
      context: ./
      dockerfile: docker/Dockerfile.boot-admin
    image: '${AUTHOR}/well-boot-admin:${TAG}'
    container_name: 'well-boot-admin'
    ports:
      - "8010:8010"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

  well-gateway:
    build:
      context: ./
      dockerfile: docker/Dockerfile.gateway
    image: '${AUTHOR}/well-gateway:${TAG}'
    container_name: 'well-gateway'
    ports:
      - "9000:9000"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

  well-provider-user:
    build:
      context: ./
      dockerfile: docker/Dockerfile.provider-user
    image: '${AUTHOR}/well-provider-user:${TAG}'
    container_name: 'well-provider-user'
    ports:
      - "9010:9010"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

networks:
  cloud:
    driver: bridge