version: "3.7"
services:
  well-boot-admin:
    build:
      context: ./
      dockerfile: docker/Dockerfile.boot-admin
    image: '${AUTHOR}/well-boot-admin:${TAG}'
    container_name: 'well-boot-admin'
    ports:
      - "8010:8010"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

  well-config:
    build:
      context: ./
      dockerfile: docker/Dockerfile.config
    image: '${AUTHOR}/well-config:${TAG}'
    container_name: 'well-config'
    ports:
      - "8888:8888"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

  well-gateway:
    build:
      context: ./
      dockerfile: docker/Dockerfile.gateway
    image: '${AUTHOR}/well-gateway:${TAG}'
    container_name: 'well-gateway'
    ports:
      - "9000:9000"
      - "5500:5500"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'zipkin.list=${ZIPKIN_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud
    depends_on:
      - well-config

  well-zipkin:
    build:
      context: ./
      dockerfile: docker/Dockerfile.zipkin
    image: '${AUTHOR}/well-zipkin:${TAG}'
    container_name: 'well-zipkin'
    ports:
      - "9411:9411"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

  well-provider-user:
    build:
      context: ./
      dockerfile: docker/Dockerfile.provider-user
    image: '${AUTHOR}/well-provider-user:${TAG}'
    container_name: 'well-provider-user'
    ports:
      - "9010:9010"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud
    depends_on:
      - well-config

networks:
  cloud:
    driver: bridge