version: "3.7"
services:
  well-boot-admin:
    container_name: well-boot-admin
    image: com.zxk175/well-boot-admin:1.0.0
    ports:
      - "8010:8010"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

  well-zuul:
    container_name: well-zuul
    image: com.zxk175/well-zuul:1.0.0
    ports:
      - "9000:9000"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

  well-provider-user:
    container_name: well-provider-user
    image: com.zxk175/well-provider-user:1.0.0
    ports:
      - "9010:9010"
    environment:
      - 'eureka.list=${EUREKA_LIST}'
      - 'spring.profiles.active=${ACTIVE}'
    networks:
      - cloud

networks:
  cloud:
    driver: bridge