version: "3.7"
services:
  well-boot-admin:
    container_name: well-boot-admin
    image: com.zxk175/well-boot-admin:1.0.0
    ports:
      - "8010:8010"
    environment:
      - 'spring.profiles.active=docker'
      - 'eureka.list=http://root:root@peer1:8001/eureka/,http://root:root@peer2:8002/eureka/,http://root:root@peer3:8003/eureka/'
    networks:
      - cloud

  well-zuul:
    container_name: well-zuul
    image: com.zxk175/well-zuul:1.0.0
    ports:
      - "9000:9000"
    environment:
      - 'spring.profiles.active=docker'
      - 'eureka.list=http://root:root@peer1:8001/eureka/,http://root:root@peer2:8002/eureka/,http://root:root@peer3:8003/eureka/'
    networks:
      - cloud

  well-provider-user:
    container_name: well-provider-user
    image: com.zxk175/well-provider-user:1.0.0
    ports:
      - "9010:9010"
    environment:
      - 'spring.profiles.active=docker'
      - 'eureka.list=http://root:root@peer1:8001/eureka/,http://root:root@peer2:8002/eureka/,http://root:root@peer3:8003/eureka/'
    networks:
      - cloud

networks:
  cloud:
    driver: bridge