version: "3"
services:
  well-boot-admin:
    container_name: well-boot-admin-1.0.0
    image: com.zxk175/well-boot-admin:1.0.0
    ports:
      - "8010:8010"
    environment:
      - 'spring.profiles.active=docker'
    networks:
      - cloud
    depends_on:
      - well-eureka

  well-zuul:
    container_name: well-zuul-1.0.0
    image: com.zxk175/well-zuul:1.0.0
    ports:
      - "9000:9000"
    environment:
      - 'spring.profiles.active=docker'
    networks:
      - cloud
    depends_on:
      - well-eureka

  well-provider-user:
    container_name: well-provider-user-1.0.0
    image: com.zxk175/well-provider-user:1.0.0
    ports:
      - "9010:9010"
    environment:
      - 'spring.profiles.active=docker'
    networks:
      - cloud
    depends_on:
      - well-eureka

networks:
  cloud:
    driver: bridge