version: "3.7"
services:
  peer1:
    build:
      context: ./
      dockerfile: docker/Dockerfile-eureka
    container_name: peer1
    # 宿主机端口:容器端口
    ports:
      - "8001:8001"
    environment:
      - 'spring.profiles.active=peer1'
    networks:
      - cloud

  peer2:
    build:
      context: ./
      dockerfile: docker/Dockerfile-eureka
    container_name: peer2
    # 宿主机端口:容器端口
    ports:
      - "8002:8002"
    environment:
      - 'spring.profiles.active=peer2'
    networks:
      - cloud

  peer3:
    build:
      context: ./
      dockerfile: docker/Dockerfile-eureka
    container_name: peer3
    # 宿主机端口:容器端口
    ports:
      - "8003:8003"
    environment:
      - 'spring.profiles.active=peer3'
    networks:
      - cloud

networks:
  cloud:
    driver: bridge