server:
  port: 8001

spring:
  profiles:
    active: peer1

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://root:root@peer2:8002/eureka/,http://root:root@peer3:8003/eureka/