spring:
  zipkin:
    base-url: ${zipkin.list}
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: ${eureka.list}

logging:
  level:
    root: info
    org.springframework.cloud.gateway: info