FROM openjdk:8-jre-alpine
LABEL maintainer="zxk175 zxk175@qq.com"

ADD well-provider/well-provider-user/build/libs/well-provider-user*.jar app.jar

ENV JAVA_OPTS="-Xmx300m -Xms300m -Djava.security.egd=file:/dev/./urandom"

ENTRYPOINT java $JAVA_OPTS -jar app.jar