FROM openjdk:8-jdk-alpine
LABEL maintainer="zxk175 zxk175@qq.com"

ADD well-base/well-gateway/build/libs/well-gateway*.jar app.jar
ENV JAVA_OPTS="-Xmx300m -Xms300m -Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5500"
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -jar app.jar" ]