FROM openjdk:8-jdk-alpine
LABEL maintainer=zxk175

ADD well-zuul-server/build/libs/well-zuul-1.0.0.jar app.jar
RUN sh -c 'touch app.jar'
ENV JAVA_OPTS="-Xmx300m -Xms300m"
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -jar app.jar" ]