FROM openjdk:8-jre-alpine
LABEL maintainer="zxk175 zxk175@qq.com"

ADD well-monitor/well-zipkin/build/libs/well-zipkin*.jar app.jar

ENV JAVA_OPTS="-Xmx300m -Xms300m -Djava.security.egd=file:/dev/./urandom"

ENTRYPOINT java $JAVA_OPTS -jar app.jar