server:
  port: 8001
  use-forward-headers: true
  undertow:
    io-threads: 4
    buffer-size: 1024
    worker-threads: 20
    direct-buffers: true

spring:
  application:
    name: eureka-server
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    user:
      name: root
      password: root

eureka:
  instance:
    # 解决/actuator/health（401 Unauthorized)
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    # 清理无效节点时间间隔
    eviction-interval-timer-in-ms: 3000
  client:
    # 是否将自己注册到服务中心，默认true
    register-with-eureka: false
    # 是否从服务中心获取注册信息，默认true
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      show-details: ALWAYS