server:
  port: 8002

spring:
  profiles:
    active: peer2

eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone:
        http://${spring.security.user.name}:${spring.security.user.password}@peer1:8001/eureka
        http://${spring.security.user.name}:${spring.security.user.password}@peer3:8003/eureka