server:
  port: 8003

spring:
  profiles:
    active: peer3

eureka:
  instance:
    hostname: peer3
    prefer-ip-address: true
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://root:root@peer1:8001/eureka,http://root:root@peer2:8002/eureka