eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url: http://127.0.0.1:${server.port}/
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://root:root@127.0.0.1:8001/eureka

logging:
  level:
    root: info
