server:
  port: 9411
  use-forward-headers: true
  undertow:
    io-threads: 4
    buffer-size: 1024
    worker-threads: 20
    direct-buffers: true
  compression:
    enabled: true

spring:
  profiles:
    active: dev
  application:
    name: zipkin-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false