mysql:
  host: 127.0.0.1

spring:
  datasource:
    druid:
      username: well
      password: 123456
  redis:
    password: 123456
  zipkin:
      base-url: http://127.0.0.1:9411/

mybatis-plus:
  configuration:
    # 打印sql语句,调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    org.mybatis: trace
    com.alibaba: trace
    com.baomidou: trace